name: Python CI Build and Test

on:
  # Код main бранчіне жіберілгенде іске қосады
  push:
    branches:
      - main

jobs:
  build-and-test:
    # Жұмысты орындау үшін операциялық жүйе
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      # Репозиторий кодын виртуалды машинаға жүктейді
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      # Python ортасын орнатады
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install Dependencies
      # requirements.txt файлын пайдаланып тәуелділіктерді (pytest) орнатады
      run: pip install -r requirements.txt
      
    - name: Run Pytest
      # Тесттерді іске қосады
      run: pytest
